""" migration

Revision ID: 8c560c4a5877
Revises: d25acd21529a
Create Date: 2024-07-21 12:42:44.469289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c560c4a5877'
down_revision: Union[str, None] = 'd25acd21529a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'completed',
               existing_type=mysql.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'completed',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
